/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tanabe' at '15/09/19 13:10' with Gradle 2.7
 *
 * @author tanabe, @date 15/09/19 13:10
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
